package com.revature.models;

import java.util.List;

public class Author {

    private int author_id;
    private String name;
    private String birth_date;
    private String nationality;
    private List<Book> books; // List of books written by the author

    // No-args constructor
    public Author() {
    }

    // All-args constructor
    public Author(int author_id, String name, String birth_date, String nationality, List<Book> books) {
        this.author_id = author_id;
        this.name = name;
        this.birth_date = birth_date;
        this.nationality = nationality;
        this.books = books;
    }

    // Constructor to be used with inserts (no id, as it will be autogenerated by the DB)
    public Author(String name, String birth_date, String nationality) {
        this.name = name;
        this.birth_date = birth_date;
        this.nationality = nationality;
    }

    // Getters and setters
    public int getAuthor_id() {
        return author_id;
    }

    public void setAuthor_id(int author_id) {
        this.author_id = author_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBirth_date() {
        return birth_date;
    }

    public void setBirth_date(String birth_date) {
        this.birth_date = birth_date;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public List<Book> getBooks() {
        return books;
    }

    public void setBooks(List<Book> books) {
        this.books = books;
    }

    // toString
    @Override
    public String toString() {
        return "Author{" +
                "author_id=" + author_id +
                ", name='" + name + '\'' +
                ", birth_date='" + birth_date + '\'' +
                ", nationality='" + nationality + '\'' +
                ", books=" + books +
                '}';
    }
}
